"""Add verification_probability to SubmittedTitle

Revision ID: 2f554a0b52ea
Revises: 7ee05ab09371
Create Date: 2025-05-25 19:24:13.210807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f554a0b52ea'
down_revision = '7ee05ab09371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_title', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_probability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_title', schema=None) as batch_op:
        batch_op.drop_column('verification_probability')

    # ### end Alembic commands ###
