"""Initial migration with all fields

Revision ID: c2bc52b8398e
Revises: 
Create Date: 2025-05-08 10:51:50.555674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bc52b8398e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('submitted_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_text', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('matched_title', sa.String(length=500), nullable=True),
    sa.Column('matched_source', sa.String(length=100), nullable=True),
    sa.Column('disallowed_words', sa.String(length=500), nullable=True),
    sa.Column('common_patterns', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_title')
    op.drop_table('user')
    # ### end Alembic commands ###
